name = "job-automation"
main = "worker.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[browser]
binding = "MYBROWSER"

[ai]
binding = "AI"
